---
on:
  pull_request:
    branches: [ master ]

jobs:
  install:
    runs-on: 	macos-latest
    strategy:
      fail-fast: false
      matrix:
        formulae:
          [
            pivnet-cli,
          ]
    steps:
      - uses: actions/checkout@v3
      - run: brew tap pivotal-legacy/tap "file://${PWD}"
      - run: brew install ${{ matrix.formulae }}

